export default {
  invernoBrilhante:
    'https://drive.google.com/file/d/1jkc2W0Hi_t1KYqy6qp3EahK2Qs8eI03G/view',
  invernoEscuro:
    'https://drive.google.com/file/d/1uNlnp4hKVaPAy48yi7hXsL19iJYw9OJ_/view',
  invernoFrio:
    'https://drive.google.com/file/d/1hKxWe8lsJzgT1nDy4Bocc6n9efmJsx3F/view',
  outonoEscuro:
    'https://drive.google.com/file/d/1a6KKp6TxuwtXzuDiwl_r6ocp6-a5bJHb/view',
  outonoQuente:
    'https://drive.google.com/file/d/1D2N-s3zucKgkINwIS7vuFP1_f-YTgk71/view',
  outonoSuave:
    'https://drive.google.com/file/d/1lgf9ybkV7R6CyG-fhLGsGxf9WxiiQmsj/view',
  primaveraBrilhante:
    'https://drive.google.com/file/d/1oG9C1AHAEAfs7VSEV0EzGLTiXwqhS7Oh/view',
  primaveraClara:
    'https://drive.google.com/file/d/1xmaJQG2nRyl_VdZKHg-zchGoxCLkUwxv/view',
  primaveraQuente:
    'https://drive.google.com/file/d/1azS1i37D38k-prNFrzqtXCoSavRnMJhb/view',
  veraoClaro:
    'https://drive.google.com/file/d/1NnxV-xPFlRtDv94HhXGfBVhNFBAPgNp_/view',
  veraoFrio:
    'https://drive.google.com/file/d/1ALtFxwypE9Gah55r8ENk-NGBSG8TiPSr/view',
  veraoSuave:
    'https://drive.google.com/file/d/1MoK3gm2bpXkUxpEny31lcqUdgyFy4N_i/view',
};
