export default {
  invernoBrilhante:
    'https://drive.google.com/file/d/1pjxt-qi58h-HpIOF4Hn04Gprv6tI6Hy1/view',
  invernoEscuro:
    'https://drive.google.com/file/d/1JLBTC9CaEJinaQJIois56ppDuTPBY9pP/view',
  invernoFrio:
    'https://drive.google.com/file/d/1bhDfYxURBS-OCMhRtcCeinyCCFx5TGSw/view',
  outonoEscuro:
    'https://drive.google.com/file/d/1aOMOSFzE_rVrn6jYjNavqvH8ayvP8nVn/view',
  outonoQuente:
    'https://drive.google.com/file/d/1kMrpo9utr1y5wJBhlz6G0-Uyzbk1yZOZ/view',
  outonoSuave:
    'https://drive.google.com/file/d/1GJ6fyWmcmYu2kiR1JVzfRB1Iz1iBhhHl/view',
  primaveraBrilhante:
    'https://drive.google.com/file/d/1wRa4usgxoapHhgXQVLaZ8dKiHrYRU-l4/view',
  primaveraClara:
    'https://drive.google.com/file/d/1ItU_6ornOCRDttg_UfOWFqfDwo6vC8eo/view',
  primaveraQuente:
    'https://drive.google.com/file/d/1PBRmf69HD0NPP5UBv3otE6TL-l-mIPGT/view',
  veraoClaro:
    'https://drive.google.com/file/d/1lqTMAm17XwNGs-E8_4ZUZgGgpHhwiVVm/view',
  veraoFrio:
    'https://drive.google.com/file/d/1T1UBXJmbdUbOD56L8ZHIrJw9mPZIw9F6/view',
  veraoSuave:
    'https://drive.google.com/file/d/1s8ja16c4gpo-VW4ZDfvf5ZfaMvmly98z/view',
};
